// <auto-generated />
using System;
using Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(CuahangDbContext))]
    partial class CuahangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.ModelsClass.Chitietchucvu", b =>
                {
                    b.Property<Guid>("NhanvienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChucvuId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NhanvienId", "ChucvuId");

                    b.HasIndex("ChucvuId");

                    b.ToTable("Chitietchucvu", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Chucvu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chucvu", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Giohang", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("IDKhach")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDKhach");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("ID");

                    b.ToTable("Giohang", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Giohangchitiet", b =>
                {
                    b.Property<Guid>("IDGiohang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDSanpham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal")
                        .HasColumnName("Giatien");

                    b.Property<decimal>("Soluong")
                        .HasColumnType("Decimal")
                        .HasColumnName("Soluong");

                    b.HasKey("IDGiohang", "IDSanpham");

                    b.HasIndex("IDSanpham");

                    b.ToTable("GiohangChitiet", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Hoadon", b =>
                {
                    b.Property<Guid>("GiohangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachhangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhanvienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("VoucherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GiohangId");

                    b.HasIndex("KhachhangId");

                    b.HasIndex("NhanvienId");

                    b.HasIndex("VoucherId");

                    b.ToTable("Hoadon", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Khachhang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khachhang", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Nhanvien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("Id");

                    b.HasIndex("SepId");

                    b.ToTable("Nhanvien", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Sanpham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal")
                        .HasColumnName("Giatien");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("Soluong");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Ten");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("Trangthai");

                    b.HasKey("Id");

                    b.ToTable("Sanpham", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<double>("GiamGia")
                        .HasColumnType("float");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("Data.ModelsClass.Chitietchucvu", b =>
                {
                    b.HasOne("Data.ModelsClass.Chucvu", "Chucvu")
                        .WithMany("chitietchucvus")
                        .HasForeignKey("ChucvuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Chucvu");

                    b.HasOne("Data.ModelsClass.Nhanvien", "Nhanvien")
                        .WithMany("Chitietchucvus")
                        .HasForeignKey("NhanvienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhanvien");

                    b.Navigation("Chucvu");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("Data.ModelsClass.Giohangchitiet", b =>
                {
                    b.HasOne("Data.ModelsClass.Giohang", "Giohang")
                        .WithMany("Giohangchitiets")
                        .HasForeignKey("IDGiohang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Giohang2");

                    b.HasOne("Data.ModelsClass.Sanpham", "Sanpham")
                        .WithMany("Giohangchitiets")
                        .HasForeignKey("IDSanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Sanpham");

                    b.Navigation("Giohang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("Data.ModelsClass.Hoadon", b =>
                {
                    b.HasOne("Data.ModelsClass.Giohang", "Giohang")
                        .WithOne("Hoadon")
                        .HasForeignKey("Data.ModelsClass.Hoadon", "GiohangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK");

                    b.HasOne("Data.ModelsClass.Khachhang", "Khachhang")
                        .WithMany("Hoadons")
                        .HasForeignKey("KhachhangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Khachhang");

                    b.HasOne("Data.ModelsClass.Nhanvien", "Nhanvien")
                        .WithMany("Hoadons")
                        .HasForeignKey("NhanvienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Nhanvien11");

                    b.HasOne("Data.ModelsClass.Voucher", null)
                        .WithMany("Hoadons")
                        .HasForeignKey("VoucherId");

                    b.Navigation("Giohang");

                    b.Navigation("Khachhang");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("Data.ModelsClass.Nhanvien", b =>
                {
                    b.HasOne("Data.ModelsClass.Nhanvien", "Sep")
                        .WithMany("Nhanviens")
                        .HasForeignKey("SepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Sep");

                    b.Navigation("Sep");
                });

            modelBuilder.Entity("Data.ModelsClass.Chucvu", b =>
                {
                    b.Navigation("chitietchucvus");
                });

            modelBuilder.Entity("Data.ModelsClass.Giohang", b =>
                {
                    b.Navigation("Giohangchitiets");

                    b.Navigation("Hoadon")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.ModelsClass.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("Data.ModelsClass.Nhanvien", b =>
                {
                    b.Navigation("Chitietchucvus");

                    b.Navigation("Hoadons");

                    b.Navigation("Nhanviens");
                });

            modelBuilder.Entity("Data.ModelsClass.Sanpham", b =>
                {
                    b.Navigation("Giohangchitiets");
                });

            modelBuilder.Entity("Data.ModelsClass.Voucher", b =>
                {
                    b.Navigation("Hoadons");
                });
#pragma warning restore 612, 618
        }
    }
}
